### ISSUE TITLE
Error: SkypeWeb adapter failure in initial login!

### ISSUE THREAD

**Issue by sbozzie** [sdimkov/hubot-skype-web#18]
Since this morning, hubot has been unable to connect with the following screenshot taken:
![login-failure](https://cloud.githubusercontent.com/assets/4300375/12397463/415d3694-be05-11e5-84d5-7a20376a254f.png)

```
C:\hubot>bin\hubot
[Mon Jan 18 2016 16:40:50 GMT+0000 (GMT Standard Time)] ERROR Timeout in waiting for login success!
[Mon Jan 18 2016 16:40:51 GMT+0000 (GMT Standard Time)] ERROR Screenshot saved at: C:\hubot\login-failure.png
[Mon Jan 18 2016 16:40:51 GMT+0000 (GMT Standard Time)] ERROR Error: SkypeWeb adapter failure in initial login!
  at Object.error (C:\hubot\node_modules\hubot-skype-web\src\skypeweb.coffee:58:17)
  at C:\hubot\node_modules\hubot-skype-web\src\skypeweb.coffee:120:22
  at Proto.apply (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\node_modules\dnode-protocol\index.js:123:13)
  at Proto.handle (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\node_modules\dnode-protocol\index.js:99:19)
  at D.dnode.handle (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\lib\dnode.js:140:21)
  at D.dnode.write (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\lib\dnode.js:128:22)
  at SockJSConnection.ondata (stream.js:31:26)
  at emitOne (events.js:77:13)
  at SockJSConnection.emit (events.js:169:7)
  at Session.didMessage (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\transport.js:220:25)
  at WebSocketReceiver.didMessage (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\trans-websocket.js:102:40)
  at C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\trans-websocket.js:75:22
  at [object Object].<anonymous> (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:41:7)
  at Array.forEach (native)
  at [object Object].EventTarget.dispatchEvent (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:40:33)
  at [object Object].API.receive (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api.js:30:10)
  at [object Object].instance._emitFrame (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\hybi_parser.js:285:44)
  at [object Object].instance.parse (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\hybi_parser.js:143:18)
  at Socket.<anonymous> (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket.js:72:33)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

**Comment by sbozzie** [comment]
This has stopped happening, with no intervention - assuming a Skype change.

**Comment by sdimkov** [comment]
Sorry I didn't write earlier.. I'm closing this now.
