### ISSUE TITLE
Hubot login failure

### ISSUE THREAD

**Issue by sbozzie** [sdimkov/hubot-skype-web#23]
On startup of Hubot,

```
C:\hubot>bin\hubot
[Fri Feb 26 2016 09:53:31 GMT+0000 (GMT Standard Time)] ERROR Timeout in waiting for login success!
[Fri Feb 26 2016 09:53:31 GMT+0000 (GMT Standard Time)] ERROR Screenshot saved at: C:\hubot\login-failure.png
[Fri Feb 26 2016 09:53:32 GMT+0000 (GMT Standard Time)] ERROR Error: SkypeWeb adapter failure in initial login!
  at Object.error (C:\hubot\node_modules\hubot-skype-web\src\skypeweb.coffee:66:17)
  at C:\hubot\node_modules\hubot-skype-web\src\skypeweb.coffee:128:22
  at Proto.apply (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\node_modules\dnode-protocol\index.js:123:13)
  at Proto.handle (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\node_modules\dnode-protocol\index.js:99:19)
  at D.dnode.handle (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\lib\dnode.js:140:21)
  at D.dnode.write (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\lib\dnode.js:128:22)
  at SockJSConnection.ondata (stream.js:31:26)
  at emitOne (events.js:77:13)
  at SockJSConnection.emit (events.js:169:7)
  at Session.didMessage (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\transport.js:220:25)
  at WebSocketReceiver.didMessage (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\trans-websocket.js:102:40)
  at C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\trans-websocket.js:75:22
  at [object Object].<anonymous> (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:41:7)
  at Array.forEach (native)
  at [object Object].EventTarget.dispatchEvent (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:40:33)
  at [object Object].API.receive (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api.js:30:10)
  at [object Object].instance._emitFrame (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\hybi_parser.js:285:44)
  at [object Object].instance.parse (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\hybi_parser.js:143:18)
  at Socket.<anonymous> (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket.js:72:33)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)

```

Image of login failure:
![login-failure](https://cloud.githubusercontent.com/assets/4300375/13401829/a1553544-df05-11e5-9ef2-962d1c85fd53.png)

**Comment by sbozzie** [comment]
With this fix, still getting the following dump on startup:

```
C:\hubot>bin\hubot
[Tue Mar 29 2016 10:19:23 GMT+0100 (GMT Daylight Time)] ERROR Timeout in waiting for login success!
[Tue Mar 29 2016 10:19:23 GMT+0100 (GMT Daylight Time)] ERROR Screenshot saved at: C:\hubot\login-failure.png
[Tue Mar 29 2016 10:19:23 GMT+0100 (GMT Daylight Time)] ERROR Error: SkypeWeb adapter failure in initial login!
  at Object.error (C:\hubot\node_modules\hubot-skype-web\src\skypeweb.coffee:66:17)
  at C:\hubot\node_modules\hubot-skype-web\src\skypeweb.coffee:128:22  at Proto.apply (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\node_modules\dnode-protocol\index.js:123:13)
  at Proto.handle (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\node_modules\dnode-protocol\index.js:99:19)
  at D.dnode.handle (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\lib\dnode.js:140:21)
  at D.dnode.write (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\dnode\lib\dnode.js:128:22)
  at SockJSConnection.ondata (stream.js:31:26)
  at emitOne (events.js:77:13)
  at SockJSConnection.emit (events.js:169:7)
  at Session.didMessage (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\transport.js:220:25)
  at WebSocketReceiver.didMessage (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\trans-websocket.js:102:40)
  at C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\trans-websocket.js:75:22
  at [object Object].<anonymous> (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:41:7)
  at Array.forEach (native)
  at [object Object].EventTarget.dispatchEvent (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:40:33)
  at [object Object].API.receive (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\api.js:30:10)
  at [object Object].instance._emitFrame (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\hybi_parser.js:285:44)
  at [object Object].instance.parse (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket\hybi_parser.js:143:18)
  at Socket.<anonymous> (C:\hubot\node_modules\hubot-skype-web\node_modules\phantom\node_modules\shoe\node_modules\sockjs\node_modules\faye-websocket\lib\faye\websocket.js:72:33)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)

```

![login-failure](https://cloud.githubusercontent.com/assets/4300375/14103473/4191f936-f598-11e5-9e6d-eab05e56782a.png)

**Comment by mxiamxia** [comment]
I got the same error, any solution on it yet?

**Comment by sbozzie** [comment]
No solution yet, but I'm closing this as a duplicate of #21
